name: jtech_tasklist

services:
  database:
    image: postgres:15-alpine
    container_name: jtech_tasklist_db
    environment:
      POSTGRES_DB: jtech_tasklist_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tasklist-network

  api:
    build:
      context: ..
      dockerfile: composer/Dockerfile
    container_name: jtech_tasklist_api
    environment:
      PROFILE: docker
      DS_URL: database
      DS_PORT: 5432
      DS_DATABASE: jtech_tasklist_database
      DS_USER: postgres
      DS_PASS: postgres
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - tasklist-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  tasklist-network:
    driver: bridge
